---
- hosts: localhost
  vars:
    namespacens: mynamespacens1
    resource_group: myresourcegroup
    location: centralindia
  tasks:
    - name: Create the namespace
      azure.azcollection.azure_rm_servicebus:
        auth_source: 537a29e1-2d93-4240-a320-42099bade9cb
        resource_group: "{{ resource_group }}"
        name: "{{ namespacens }}"
        location: "{{ location }}"
