---
- name: Create the resource group
  hosts: all
  become: true
  tasks:
  - name: Create a resource group
    azure.azcollection.azure_rm_resourcegroup:
      name: myResourceGroup
      location: eastus

