---
- hosts: localhost
  vars:
    namespacens: mynamespacens1
    resource_group: myresourcegroup
    location: centralindia
  tasks:
    - name: Create the namespace
      azure.azcollection.azure_rm_servicebus:
        auth_source: env
        resource_group: "{{ resource_group }}"
        name: "{{ namespacens }}"
        location: "{{ location }}"
